### ISSUE TITLE
Google translate written over manual corrections

### ISSUE THREAD

**Issue by james-interest** [niftylettuce/mandarin#6]
Thanks for creating 'mandarin', it's been super to get a quick translation of `.json` files.

The ability to use the redis cache is also great. I'm seeing the following and not sure if it's part of the expected behaviour or not:

When I run mandarin the first time everything is correctly generated, then I make manually modifications in the results produced by Google Translate (`fr.json`...), then run mandarin again and it writes over the manual modifications.

My set up may be stale so I can try again with a fresh installation of Redis, but some clarification around that would be great. I'll be happy to add anything to the README or code through a PR if needed.

**Comment by niftylettuce** [comment]
PR welcome!
